### ISSUE TITLE
NPDE package has been removed from CRAN

### ISSUE THREAD

**Issue by TingjieGuo** [ecomets/npdeMarcExtensions#1]
Hi Emmanuelle, (if this is the right place)

Just a reminder if you don't know it yet. I found NPDE package having been removed from the CRAN repo. Is this package still maintained?

Cheers,
TJ

**Comment by ecomets** [comment]
A new version (npde 3.0, followed by 3.1 and 3.2) is now on CRAN :-)
Sorry for the delay, there was a significant overhaul of the package which took more time than anticipated.
Best regards,
Emmanuelle
